"""Constants for VAE modeling."""

INPUT_DIM = 1280
LATENT_DIM = 256
HIDDEN_DIM = 512

NUM_EPOCHS = 100
BATCH_SIZE = 128
PATIENCE = 7
LEARNING_RATE = 8e-5
DROPOUT_RATE = 0.2
WEIGHT_DECAY = 2e-6

RL_WEIGHT = 1.0
KL_WEIGHT = 0.2
PL_WEIGHT = 1.0
SEQ_WEIGHT = 1.0

OPTIM_STEPS = 25
OPTIM_LR = 0.05

AA_ALPHABET = "ACDEFGHIKLMNPQRSTVWY"
AA_VOCAB = {aa: i for i, aa in enumerate(AA_ALPHABET)}
VOCAB_SIZE = len(AA_VOCAB) + 1  # 20 AAs + 1 for padding/unknown
